### ISSUE TITLE
breakECDSA.py error

### ISSUE THREAD

**Issue by tmaljay** [demining/CryptoDeepTools#19]
Traceback (most recent call last):
  File "C:\Users\tmalj_thhn\Downloads\Bitcoin-Wallet-Recovery-main\Bitcoin-Wallet-Recovery-main\Sources\breakECDSA.py", line 11, in <module>
    e = txnUtils.getSignableTxn(m)
  File "C:\Users\tmalj_thhn\Downloads\Bitcoin-Wallet-Recovery-main\Bitcoin-Wallet-Recovery-main\Sources\txnUtils.py", line 53, in getSignableTxn
    inputAddr = base58.b58decode_check(keyUtils.pubKeyToAddr(pub))
  File "C:\Users\tmalj_thhn\Downloads\Bitcoin-Wallet-Recovery-main\Bitcoin-Wallet-Recovery-main\Sources\keyUtils.py", line 55, in pubKeyToAddr
    ripemd160.update(hashlib.sha256(s.decode('hex')).digest())
AttributeError: 'str' object has no attribute 'decode'

**Comment by demining** [comment]
@tmaljay Thing is that earlier when I did the review it worked on UBUNTU 18.04. Now Google has updated its Google Colab service to version UBUNTU 22.04. I can suggest you install the old version of UBUNTU 18.04 on your PC and run everything through the terminal as shown in the article and in the video .
In addition, the "hashlib" module, which is installed by default, does not work properly, because Some cryptographic algorithms are missing, for example there is no RIPEMD160 algorithm and therefore we cannot reproduce base58.

_To check, I ran the code:_

```
import hashlib

for name in hashlib.algorithms_available:
    try:
        hashlib.new(name)
        print('ok', name)
    except ValueError:
        print('error', name)
```


![image](https://github.com/demining/CryptoDeepTools/assets/87700947/2ffab664-c56b-4fbd-9746-81fe76ee9d8f)


**Cryptographic algorithm: RIPEMD160 missing :(**

**It will be better if you do everything on your PC, install version UBUNTU 18.04**

**Comment by tmaljay** [comment]
Thanks for taking time out to respond. I am currently installing UBUNTU 18.04, I will keep you posted on my progress and hopefully someone else can in the future use this as reference point.

**Comment by mzluckylady6969** [comment]
Working through the issues today I'll have them solved by tomorrow afternoon
